apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bandmate
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cGFzc3dvcmQ=  # password
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: bandmate
type: Opaque
data:
  secret: YmFuZG1hdGUtcHJvZC1zZWNyZXQta2V5LWZvci1qd3Q=  # bandmate-prod-secret-key-for-jwt
