apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: bandmate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: bandmate-client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.bandmate.com/api"
        - name: NEXT_PUBLIC_GRAPHQL_URL
          value: "https://api.bandmate.com/graphql"
        - name: NEXT_PUBLIC_SOCKET_URL
          value: "https://api.bandmate.com"
        - name: NEXT_PUBLIC_TOKEN_NAME
          value: "bandmate_token"
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "150m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: bandmate
spec:
  selector:
    app: client
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
